"""asss

Revision ID: a5fd4132faf2
Revises: 4b427116fcd1
Create Date: 2020-02-03 02:14:28.271839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5fd4132faf2'
down_revision = '4b427116fcd1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('finish', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('time_working', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'time_working')
    op.drop_column('tasks', 'finish')
    # ### end Alembic commands ###
