"""timeworkingtext2ww

Revision ID: 71df2e9c1ff6
Revises: fa9c547a631a
Create Date: 2020-02-03 02:54:59.522927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71df2e9c1ff6'
down_revision = 'fa9c547a631a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('time_working', sa.text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'time_working')
    # ### end Alembic commands ###
