"""active3

Revision ID: 94e618eba9db
Revises: f36db8055065
Create Date: 2020-02-03 15:34:49.428494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e618eba9db'
down_revision = 'f36db8055065'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('active_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'active_date')
    # ### end Alembic commands ###
