"""active10

Revision ID: df1213ba2774
Revises: 5bdb9cc8f5d2
Create Date: 2020-02-03 17:16:12.677962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1213ba2774'
down_revision = '5bdb9cc8f5d2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
