"""aver2

Revision ID: f78821c04862
Revises: 1695682af089
Create Date: 2020-02-03 02:08:09.799104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78821c04862'
down_revision = '1695682af089'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('finish', sa.DateTime(), nullable=False))
    op.add_column('tasks', sa.Column('time_working', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'time_working')
    op.drop_column('tasks', 'finish')
    # ### end Alembic commands ###
