"""active4

Revision ID: ac138021468c
Revises: 94e618eba9db
Create Date: 2020-02-03 15:36:05.508647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac138021468c'
down_revision = '94e618eba9db'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
