"""ts

Revision ID: 967778189e51
Revises: 71df2e9c1ff6
Create Date: 2020-02-03 02:57:16.160611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967778189e51'
down_revision = '71df2e9c1ff6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
