"""active9

Revision ID: 5bdb9cc8f5d2
Revises: 7e03f1331817
Create Date: 2020-02-03 16:10:18.758593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bdb9cc8f5d2'
down_revision = '7e03f1331817'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
