"""active11

Revision ID: 09bed1b90788
Revises: df1213ba2774
Create Date: 2020-02-03 17:17:02.557719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09bed1b90788'
down_revision = 'df1213ba2774'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
