"""agregamos imagen3

Revision ID: a7e961e3806a
Revises: 3c24c6b7468e
Create Date: 2020-01-28 01:13:55.138438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e961e3806a'
down_revision = '3c24c6b7468e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
