"""timeworkSS

Revision ID: 52be5216a2c2
Revises: 5e19bc8260f9
Create Date: 2020-02-03 00:42:50.069844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52be5216a2c2'
down_revision = '5e19bc8260f9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('time_working', sa.text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'time_working')
    # ### end Alembic commands ###
