"""agregamos imagen2

Revision ID: 3c24c6b7468e
Revises: 3e01d5136e8c
Create Date: 2020-01-28 01:12:33.038535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c24c6b7468e'
down_revision = '3e01d5136e8c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
