"""exekenwin23

Revision ID: 0c0fb3a2bb67
Revises: 486b35620a95
Create Date: 2020-01-25 03:41:09.887162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0fb3a2bb67'
down_revision = '486b35620a95'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
