"""agregamos imagen

Revision ID: 3e01d5136e8c
Revises: 9cd04bc3bec3
Create Date: 2020-01-28 00:39:45.769230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e01d5136e8c'
down_revision = '9cd04bc3bec3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image')
    # ### end Alembic commands ###
