"""cambiamos rol

Revision ID: 9cd04bc3bec3
Revises: 0c0fb3a2bb67
Create Date: 2020-01-25 14:10:36.205451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd04bc3bec3'
down_revision = '0c0fb3a2bb67'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_role', 'users', type_='unique')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_role', 'users', ['role'])
    # ### end Alembic commands ###
