"""timeworking

Revision ID: 717533e7f03a
Revises: 3b17bfc97b9b
Create Date: 2020-02-03 00:29:20.146134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717533e7f03a'
down_revision = '3b17bfc97b9b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('time_working', sa.text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'time_working')
    # ### end Alembic commands ###
