"""coso

Revision ID: 1a8a4764b575
Revises: 1f0d5c5929de
Create Date: 2020-02-03 01:20:17.964188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8a4764b575'
down_revision = '1f0d5c5929de'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('finish', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'finish')
    # ### end Alembic commands ###
