"""tsfw

Revision ID: 7510cd1075a2
Revises: 83f95b4c1919
Create Date: 2020-02-03 04:09:41.914752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7510cd1075a2'
down_revision = '83f95b4c1919'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
